export const testimonials = [
  {
    img: "https://randomuser.me/api/portraits/men/1.jpg",
    username: "john_doe01",
    name: "John Doe",
    feedback: "Fantastic platform for collaboration.",
  },
  {
    img: "https://randomuser.me/api/portraits/women/2.jpg",
    username: "jane_smith",
    name: "Jane Smith",
    feedback: "Absolutely love using Collaborite!",
  },
  {
    img: "https://randomuser.me/api/portraits/men/3.jpg",
    username: "mike_johnson",
    name: "Mike Johnson",
    feedback: "Great tool for remote team work.",
  },
  {
    img: "https://randomuser.me/api/portraits/women/4.jpg",
    username: "emily_davis",
    name: "Emily Davis",
    feedback: "Makes editing together seamless.",
  },
  {
    img: "https://randomuser.me/api/portraits/women/5.jpg",
    username: "sarah_brown",
    name: "Sarah Brown",
    feedback: "A must-have for any team.",
  },
  {
    img: "https://randomuser.me/api/portraits/men/6.jpg",
    username: "chris_wilson",
    name: "Chris Wilson",
    feedback: "Incredible user experience.",
  },
  {
    img: "https://randomuser.me/api/portraits/women/7.jpg",
    username: "jessica_taylor",
    name: "Jessica Taylor",
    feedback: "Highly recommend it!",
  },
  {
    img: "https://randomuser.me/api/portraits/men/8.jpg",
    username: "david_anderson",
    name: "David Anderson",
    feedback: "Very user-friendly and effective.",
  },
  {
    img: "https://randomuser.me/api/portraits/women/9.jpg",
    username: "megan_thompson",
    name: "Megan Thompson",
    feedback: "Perfect for our needs.",
  },
  {
    img: "https://randomuser.me/api/portraits/men/10.jpg",
    username: "james_white",
    name: "James White",
    feedback: "Love the real-time editing features.",
  },
  {
    img: "https://randomuser.me/api/portraits/women/11.jpg",
    username: "laura_martinez",
    name: "Laura Martinez",
    feedback: "Super efficient and easy to use.",
  },
  {
    img: "https://randomuser.me/api/portraits/men/12.jpg",
    username: "robert_lee",
    name: "Robert Lee",
    feedback: "Great tool for productivity.",
  },
  {
    img: "https://randomuser.me/api/portraits/women/13.jpg",
    username: "anna_harris",
    name: "Anna Harris",
    feedback: "Collaborite is a game-changer.",
  },
  {
    img: "https://randomuser.me/api/portraits/men/14.jpg",
    username: "brian_clark",
    name: "Brian Clark",
    feedback: "Can't imagine working without it.",
  },
  {
    img: "https://randomuser.me/api/portraits/women/15.jpg",
    username: "linda_lewis",
    name: "Linda Lewis",
    feedback: "Our team loves it.",
  },
  {
    img: "https://randomuser.me/api/portraits/men/16.jpg",
    username: "kevin_robinson",
    name: "Kevin Robinson",
    feedback: "Simply amazing!",
  },
  {
    img: "https://randomuser.me/api/portraits/women/17.jpg",
    username: "olivia_walker",
    name: "Olivia Walker",
    feedback: "Exceptional tool for collaboration.",
  },
  {
    img: "https://randomuser.me/api/portraits/men/18.jpg",
    username: "matthew_hall",
    name: "Matthew Hall",
    feedback: "Great features and easy to use.",
  },
  {
    img: "https://randomuser.me/api/portraits/women/19.jpg",
    username: "sophia_young",
    name: "Sophia Young",
    feedback: "Very helpful for team projects.",
  },
  {
    img: "https://randomuser.me/api/portraits/men/20.jpg",
    username: "daniel_allen",
    name: "Daniel Allen",
    feedback: "Effortless and intuitive.",
  },
  {
    img: "https://randomuser.me/api/portraits/women/21.jpg",
    username: "chloe_king",
    name: "Chloe King",
    feedback: "An indispensable tool for us.",
  },
  {
    img: "https://randomuser.me/api/portraits/men/22.jpg",
    username: "jason_wright",
    name: "Jason Wright",
    feedback: "Outstanding performance.",
  },
  {
    img: "https://randomuser.me/api/portraits/women/23.jpg",
    username: "victoria_scott",
    name: "Victoria Scott",
    feedback: "Makes teamwork a breeze.",
  },
  {
    img: "https://randomuser.me/api/portraits/men/24.jpg",
    username: "nathan_green",
    name: "Nathan Green",
    feedback: "Absolutely fantastic!",
  },
  {
    img: "https://randomuser.me/api/portraits/women/25.jpg",
    username: "ella_adams",
    name: "Ella Adams",
    feedback: "Our go-to tool for editing.",
  },
  {
    img: "https://randomuser.me/api/portraits/men/26.jpg",
    username: "andrew_baker",
    name: "Andrew Baker",
    feedback: "Highly efficient and reliable.",
  },
  {
    img: "https://randomuser.me/api/portraits/women/27.jpg",
    username: "zoe_gonzalez",
    name: "Zoe Gonzalez",
    feedback: "Great support and features.",
  },
  {
    img: "https://randomuser.me/api/portraits/men/28.jpg",
    username: "joseph_perez",
    name: "Joseph Perez",
    feedback: "A revolutionary tool for us.",
  },
  {
    img: "https://randomuser.me/api/portraits/women/29.jpg",
    username: "grace_nelson",
    name: "Grace Nelson",
    feedback: "Smooth and easy to navigate.",
  },
  {
    img: "https://randomuser.me/api/portraits/men/30.jpg",
    username: "anthony_carter",
    name: "Anthony Carter",
    feedback: "Makes collaboration effortless.",
  },
  {
    img: "https://randomuser.me/api/portraits/women/31.jpg",
    username: "lily_mitchell",
    name: "Lily Mitchell",
    feedback: "Simply the best collaboration tool.",
  },
  {
    img: "https://randomuser.me/api/portraits/men/32.jpg",
    username: "thomas_roberts",
    name: "Thomas Roberts",
    feedback: "Easy to set up and use.",
  },
  {
    img: "https://randomuser.me/api/portraits/women/33.jpg",
    username: "sophie_turner",
    name: "Sophie Turner",
    feedback: "Love the user-friendly interface.",
  },
  {
    img: "https://randomuser.me/api/portraits/men/34.jpg",
    username: "christopher_phillips",
    name: "Christopher Phillips",
    feedback: "Perfect for our workflow.",
  },
  {
    img: "https://randomuser.me/api/portraits/women/35.jpg",
    username: "mia_campbell",
    name: "Mia Campbell",
    feedback: "The best tool for editing together.",
  },
  {
    img: "https://randomuser.me/api/portraits/men/36.jpg",
    username: "joshua_evans",
    name: "Joshua Evans",
    feedback: "Highly recommend to everyone.",
  },
  {
    img: "https://randomuser.me/api/portraits/women/37.jpg",
    username: "isabella_parker",
    name: "Isabella Parker",
    feedback: "Fantastic features and support.",
  },
  {
    img: "https://randomuser.me/api/portraits/men/38.jpg",
    username: "ethan_edwards",
    name: "Ethan Edwards",
    feedback: "Great for remote collaboration.",
  },
  {
    img: "https://randomuser.me/api/portraits/women/39.jpg",
    username: "ava_collins",
    name: "Ava Collins",
    feedback: "Our team loves using it.",
  },
  {
    img: "https://randomuser.me/api/portraits/men/40.jpg",
    username: "alexander_stewart",
    name: "Alexander Stewart",
    feedback: "A must-have for any team.",
  },
  {
    img: "https://randomuser.me/api/portraits/women/41.jpg",
    username: "maya_sanchez",
    name: "Maya Sanchez",
    feedback: "Simply incredible!",
  },
  {
    img: "https://randomuser.me/api/portraits/men/42.jpg",
    username: "jack_morris",
    name: "Jack Morris",
    feedback: "Boosts our productivity.",
  },
  {
    img: "https://randomuser.me/api/portraits/women/43.jpg",
    username: "natalie_rogers",
    name: "Natalie Rogers",
    feedback: "Love the collaborative features.",
  },
  {
    img: "https://randomuser.me/api/portraits/men/44.jpg",
    username: "ryan_cook",
    name: "Ryan Cook",
    feedback: "Efficient and user-friendly.",
  },
  {
    img: "https://randomuser.me/api/portraits/women/45.jpg",
    username: "hannah_morgan",
    name: "Hannah Morgan",
    feedback: "Highly effective for teamwork.",
  },
];
